# Generated by Django 3.1.5 on 2021-01-26 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bases',
            fields=[
                ('codi', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Consultes',
            fields=[
                ('codi', models.IntegerField(primary_key=True, serialize=False)),
                ('pregunta', models.TextField()),
                ('pista', models.TextField()),
                ('base_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruleta_c.bases')),
            ],
        ),
        migrations.CreateModel(
            name='Respostes',
            fields=[
                ('codi', models.IntegerField(primary_key=True, serialize=False)),
                ('resposta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Solucions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruleta_c.consultes')),
                ('codi_resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruleta_c.respostes')),
            ],
        ),
    ]
